#Thanks and credits to https://github.com/docker/awesome-compose/blob/master/spring-postgres/docker-compose.yaml

version: "0.9"
services:   
  db:
    image: postgres:alpine
    restart: always    
    volumes:
      - db-data:/var/lib/postgresql/data    
    environment:
      - POSTGRES_DB=a_db_name
      - POSTGRES_PASSWORD=a1w2rfs
      - POSTGRES_USER = peaceful
    expose:
      - 5432
  backend:
    image: jlmacle/atl-back-end:v0.9
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - DB_url=jdbc:postgresql://postgresql:5432/a_db_name
      - DB_USERNAME=peaceful
      - DB_PASSWORD=a1w2rfs   
  frontend:
    image: jlmacle/atl-front-end:v0.9
    ports:
      - 4200:4200    
    expose:
     - 4200    
  
volumes:
  db-data:

networks:
  atl-network: {}
