#Thanks to https://github.com/docker/awesome-compose/blob/master/spring-postgres/docker-compose.yaml
version: "3.4"
services:
  postgresql:
    image: postgres:alpine
    restart: always    
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - atl-network
    expose:
      - 5432
  
  backend:
    depends_on:
      - postgresql
    image: jlmacle/atl-back-end:v0.9
    ports:
      - 8080:8080
    expose:
      - 8080   
    networks:
      - atl-network    
  
  frontend:
    depends_on:
      - backend
    image: jlmacle/atl-front-end:v0.9
    ports:
      - 4200:80    
    expose:
     - 4200
    networks:
     - atl-network
  
 
volumes:
  db-data:

networks:
  atl-network: {}
