#Thanks to https://github.com/docker/awesome-compose/blob/master/spring-postgres/docker-compose.yaml
#https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
version: "3.5"
services:
  postgresql:
    image: postgres:alpine
    restart: always      
    networks:
      - atl-network             
    expose:
      - 5432  
  backend:
    depends_on:
      - postgresql
    image: jlmacle/atl-back-end:v0.9
    ports:
      - 8080:8080
    expose:
      - 8080   
    environment:
      - DB_URL=jdbc:postgresql://postgresql:5432/test
      - DB_USERNAME=postgres
    networks:
      - atl-network    
  
  frontend:
    depends_on:
      - backend
    image: jlmacle/atl-front-end:v0.9
    ports:
      - 4200:80    
    expose:
     - 4200
    networks:
     - atl-network

networks:
  atl-network: {}

  
