#Thanks to https://github.com/docker/awesome-compose/blob/master/spring-postgres/docker-compose.yaml
#https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
version: "3.5"
services:
  postgresql:
    image: postgres:alpine
    restart: always      
    networks:
      - atl-network     
    #environment:
      #- POSTGRES_DB=jlacl
      #- POSTGRES_USER=jlacl    
      #- POSTGRES_PASSWORD=todolist
    expose:
      - 5432
  backend:
    depends_on:
      - postgresql
    image: jlmacle/atl-back-end:v0.9
    ports:
      - 8080:8080
    expose:
      - 8080   
    environment:
      - DB_URL=jdbc:postgresql://postgresql:5432/todolist
      - DB_USERNAME=jlacl
      - DB_PASSWORD=jlacl
    networks:
      - atl-network  
 
networks:
  atl-network: {}

  
