orbs:
  pa11yci: nebulab/pa11yci@1.0.0
version: 2.1
jobs:
  #Angular server to start
  build:
    docker:
      - image: alpine:3-7
    steps:
      - run:
          name: Todo, Angular server to start
          command: echo "More to do to start an Angular server"

  #Backend server to start


  #Pa11y-ci audit
 

