# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
#Note: this may lack maturity
version: 2.1

commands:
  front-end-config-check-command:
    steps:
      - checkout
      - run: #Configuration check
          echo "Starting the configuration check." 
          && cd  src/environments/
          && grep "//static base_url="http://192" ./variables.ts
          
executors:
  front-end-executor:
    docker:
      # primary container
      # https://hub.docker.com/u/circleci/
      - image: circleci/openjdk

jobs:
  front-end-config-check-job:
    executor: front-end-executor
    steps:
      - front-end-config-check-command      

workflows:  
  front-end-config-check-workflow:
    jobs:
      - front-end-config-check-job
